name: Generate New File with Python and Commit

on:
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python generate_file.py

      - name: Clone target repo
        run: |
          git clone https://github.com/corgi-pontalk/contents.git

      - name: Commit & push to target repo
        working-directory: contents
        run: |
          cp ../articles/generated_*.txt .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          rm .gitignore
          git add .
          git commit -m "Add generated file"
          git push -u https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/corgi-pontalk/contents.git main

